/*
 * This file was automatically generated by EvoSuite
 * Thu May 09 20:30:32 GMT 2019
 */

package swtesting1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import swtesting1.VarNameEval;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VarNameEval_ESTest extends VarNameEval_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VarNameEval varNameEval0 = new VarNameEval();
      // Undeclared exception!
      try { 
        varNameEval0.isValid("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VarNameEval varNameEval0 = new VarNameEval();
      // Undeclared exception!
      try { 
        varNameEval0.isValid((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("swtesting1.VarNameEval", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VarNameEval varNameEval0 = new VarNameEval();
      boolean boolean0 = varNameEval0.isValid("3");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VarNameEval varNameEval0 = new VarNameEval();
      boolean boolean0 = varNameEval0.isValid("x1q%Z");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      VarNameEval varNameEval0 = new VarNameEval();
      boolean boolean0 = varNameEval0.isValid("AG!IWI)");
      assertFalse(boolean0);
  }
}
